### ISSUE TITLE
why i get a error when i run this code?

### ISSUE THREAD

**Issue by cikiChe** [mannheim-network/spacex-script#5]
debug: Loading config file: config.yaml
error: Failed to parse json: SyntaxError: Unexpected token y in JSON at position 0
    at JSON.parse (<anonymous>)
    at /opt/app/schema/identity.schema.js:12:49
    at Object.validate (/opt/app/node_modules/joi/lib/types/any.js:47:28)
    at Object.internals.rules (/opt/app/node_modules/joi/lib/validator.js:397:33)
    at Object.exports.validate (/opt/app/node_modules/joi/lib/validator.js:353:22)
    at internals.Base.$_validate (/opt/app/node_modules/joi/lib/base.js:773:26)
    at Object.validate (/opt/app/node_modules/joi/lib/types/keys.js:108:45)
    at Object.exports.validate (/opt/app/node_modules/joi/lib/validator.js:328:26)
    at internals.Base.$_validate (/opt/app/node_modules/joi/lib/base.js:773:26)
    at Object.validate (/opt/app/node_modules/joi/lib/types/keys.js:108:45)
    at Object.exports.validate (/opt/app/node_modules/joi/lib/validator.js:328:26)
    at Object.internals.entry (/opt/app/node_modules/joi/lib/validator.js:145:28)
    at Object.exports.entryAsync (/opt/app/node_modules/joi/lib/validator.js:58:30)
    at internals.Base.validateAsync (/opt/app/node_modules/joi/lib/base.js:553:26)
    at loadConfig (/opt/app/index.js:20:36)
    at async main (/opt/app/index.js:60:5)
error: failed to load config: 'Error code "Backup is not a valid json string" is not defined, your custom type is missing the correct messages definition'
476aa06d5bae87d43786f250e727068fd44a62c2d4637b8e12a627910225c071
[ERROR] Failed to generate application configs, please check your config.yaml

then. i check config.sh. i find  this file is genter config.yaml and the backup is string . not json string

**Comment by cikiChe** [comment]
account must write :  {“address”:"write a true address"}
